package com.adafruit.sensor;

public enum SensorType
{
	SENSOR_TYPE_ACCELEROMETER,			// Gravity + linear acceleration
	SENSOR_TYPE_MAGNETIC_FIELD,
	SENSOR_TYPE_ORIENTATION,
	SENSOR_TYPE_GYROSCOPE,
	SENSOR_TYPE_LIGHT,
	SENSOR_TYPE_PRESSURE,
	SENSOR_TYPE_PROXIMITY,
	SENSOR_TYPE_GRAVITY,
	SENSOR_TYPE_LINEAR_ACCELERATION,	// Acceleration not including gravity
	SENSOR_TYPE_ROTATION_VECTOR,
	SENSOR_TYPE_RELATIVE_HUMIDITY,
	SENSOR_TYPE_AMBIENT_TEMPERATURE,
	SENSOR_TYPE_VOLTAGE,
	SENSOR_TYPE_CURRENT,
	SENSOR_TYPE_COLOR;
}
